[COMMON] ion: add seq_file header to avoid compile error
In carveout heap, seq_printf/seq_puts functions are used, but seq_file
header was not included explictly.

drivers/staging/android/ion/ion_carveout_heap.c: In function
'carveout_heap_debug_show':
drivers/staging/android/ion/ion_carveout_heap.c:183:2: error: implicit
declaration of function 'seq_puts'
[-Werror=implicit-function-declaration]
  seq_puts(s, "\ncarveout heap allocations\n");
  ^
drivers/staging/android/ion/ion_carveout_heap.c:184:2: error: implicit
declaration of function 'seq_printf'
[-Werror=implicit-function-declaration]
  seq_printf(s, "%11.s %10.s %10.s\n", "name", "size", "free");

Compile error occurred when CONFIG_PINCTRL is not defined. Because
seq_fil header was included with below dependency.

linux/dma-mapping.h
-> linux/device.h
   -> linux/pinctrl/devinfo.h
      ifdef CONFIG_PINCTRL
      linux/pinctrl/consumer.h
      -> linux/seq_file.h
      endif

This is not intended and wrong dependency. So fixed.

Change-Id: Ief19bf275251376a21b9cb5877556088b2b28c44
Signed-off-by: Janghyuck Kim <janghyuck.kim@samsung.com>